var exampleProducts = [
    {
        "id": 38322,
        "campus": "hr-atx",
        "name": "Camo Onesie",
        "slogan": "Blend in to your crowd",
        "description": "The So Fatigues will wake you up and fit you in. This high energy camo will have you blending in to even the wildest surroundings.",
        "category": "Jackets",
        "default_price": "140.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38323,
        "campus": "hr-atx",
        "name": "Bright Future Sunglasses",
        "slogan": "You've got to wear shades",
        "description": "Where you're going you might not need roads, but you definitely need some shades. Give those baby blues a rest and let the future shine bright on these timeless lenses.",
        "category": "Accessories",
        "default_price": "69.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38324,
        "campus": "hr-atx",
        "name": "Morning Joggers",
        "slogan": "Make yourself a morning person",
        "description": "Whether you're a morning person or not.  Whether you're gym bound or not.  Everyone looks good in joggers.",
        "category": "Pants",
        "default_price": "40.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38325,
        "campus": "hr-atx",
        "name": "Slacker's Slacks",
        "slogan": "Comfortable for everything, or nothing",
        "description": "I'll tell you how great they are after I nap for a bit.",
        "category": "Pants",
        "default_price": "65.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38326,
        "campus": "hr-atx",
        "name": "Heir Force Ones",
        "slogan": "A sneaker dynasty",
        "description": "Now where da boxes where I keep mine? You should peep mine, maybe once or twice but never three times. I'm just a sneaker pro, I love Pumas and shell toes, but can't nothin compare to a fresh crispy white pearl",
        "category": "Kicks",
        "default_price": "99.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38327,
        "campus": "hr-atx",
        "name": "Pumped Up Kicks",
        "slogan": "Faster than a just about anything",
        "description": "The Pumped Up serves up crisp court style with a modern look. These shoes show off tennis-whites shades and are constructed with a supple leather upper and a classic rubber cupsole.",
        "category": "Kicks",
        "default_price": "89.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38328,
        "campus": "hr-atx",
        "name": "Blues Suede Shoes",
        "slogan": "2019 Stanley Cup Limited Edition",
        "description": "Touch down in the land of the Delta Blues in the middle of the pouring rain",
        "category": "Dress Shoes",
        "default_price": "120.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38329,
        "campus": "hr-atx",
        "name": "YEasy 350",
        "slogan": "Just jumped over jumpman",
        "description": "These stretchy knit shoes show off asymmetrical lacing and a big sculpted rubber midsole. In a nod to adidas soccer heritage.",
        "category": "Kicks",
        "default_price": "450.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38330,
        "campus": "hr-atx",
        "name": "Summer Shoes",
        "slogan": "A risky call in the spring or fall",
        "description": "Low-top panelled buffed leather and mesh sneakers. Sizing embroidered in black at round toe. Tonal lace-up closure. Pull-loop and rubberized style name at padded tongue. Padded collar. Pull-loop at heel collar. Logo embroidered in black at outer side. Tonal treaded rubber sole. Tonal stitching.",
        "category": "Kicks",
        "default_price": "59.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38331,
        "campus": "hr-atx",
        "name": "Infinity Stone",
        "slogan": "Reality is often disappointing. That is, it was. Now, reality can be whatever I want.",
        "description": "The Infinity Stones are six immensely powerful stone-like objects tied to different aspects of the universe, created by the Cosmic Entities. Each of the stones possesses unique capabilities that have been enhanced and altered by various alien civilizations for millennia.",
        "category": "Accessories",
        "default_price": "50000000.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38332,
        "campus": "hr-atx",
        "name": "Air Minis 250",
        "slogan": "Full court support",
        "description": "This optimized air cushion pocket reduces impact but keeps a perfect balance underfoot.",
        "category": "Basketball Shoes",
        "default_price": "49.00",
        "created_at": "2021-08-13T14:38:00.907Z",
        "updated_at": "2021-08-13T14:38:00.907Z"
    },
    {
        "id": 38333,
        "campus": "hr-atx",
        "name": "Rigoberto Heels",
        "slogan": "Voluptatem aut quia ut magnam excepturi itaque facilis veniam nulla.",
        "description": "Aliquid fugit illo earum voluptates hic libero recusandae quis et. Hic et et corporis ducimus itaque doloribus. Laborum rerum iste ut illo molestiae tenetur nobis. Ratione non et harum voluptas facere sed itaque ea dolorum. Aut occaecati eos et adipisci nisi aperiam et numquam suscipit.",
        "category": "Heels",
        "default_price": "5.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38334,
        "campus": "hr-atx",
        "name": "Vaughn Coat",
        "slogan": "Veritatis saepe voluptatem ut illo.",
        "description": "In omnis exercitationem et et. Incidunt soluta occaecati inventore quam nobis ducimus repellat nihil ducimus. Accusantium recusandae natus. A soluta omnis excepturi molestiae totam sunt sit quia est. Esse blanditiis aut voluptas cum. Quam quod eius aut vero libero cupiditate iste.",
        "category": "Coat",
        "default_price": "243.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38335,
        "campus": "hr-atx",
        "name": "Antoinette 1350 Sweatpants",
        "slogan": "Molestiae dolor et vel laboriosam non aut ex exercitationem ullam.",
        "description": "Hic enim dolorem qui quia excepturi ipsum. Ut architecto ipsum molestiae et tempore dolorem dicta occaecati similique. Laborum et molestias eius laborum. Sit magni rerum occaecati error vel reprehenderit accusantium quos.",
        "category": "Sweatpants",
        "default_price": "65.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38336,
        "campus": "hr-atx",
        "name": "Frederick Coat",
        "slogan": "Et ea placeat dolores et quam eos.",
        "description": "Facere soluta doloremque animi voluptas. Itaque vitae aut molestias voluptate molestiae voluptas illum. Aut reprehenderit molestiae mollitia dolores voluptatem aut sit. Quia suscipit quis impedit doloremque tempora error. Qui nisi hic explicabo dolores animi odit optio dolores consequatur. Et qui eius.",
        "category": "Coat",
        "default_price": "538.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38337,
        "campus": "hr-atx",
        "name": "Edna Boots",
        "slogan": "Dolores excepturi praesentium qui dicta enim dolores assumenda.",
        "description": "Corrupti repellendus officia ut alias labore libero. Molestiae ipsa nam eum facere minus suscipit exercitationem optio. Accusamus ad qui fuga. Quo iste nemo. Ducimus error dignissimos dolores. Eius eum nesciunt corrupti et quia dolor non doloremque.",
        "category": "Boots",
        "default_price": "226.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38338,
        "campus": "hr-atx",
        "name": "Kathryne Skirt",
        "slogan": "Enim dolore dolores cumque veritatis in a.",
        "description": "Aut ut omnis voluptatem. Ipsam facilis repellendus dolor quia tenetur sed harum quia et. Minus consequatur commodi temporibus perspiciatis sequi. Corporis similique occaecati. Ut quod voluptatem qui molestiae. Ad vero nostrum aut inventore.",
        "category": "Skirt",
        "default_price": "869.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38339,
        "campus": "hr-atx",
        "name": "Gregoria Sunglasses",
        "slogan": "Rerum dolorem occaecati.",
        "description": "Et reiciendis corrupti. Qui adipisci et fuga. Cum temporibus rerum. Ducimus debitis consequuntur est ut ut provident nemo tenetur possimus.",
        "category": "Sunglasses",
        "default_price": "232.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38340,
        "campus": "hr-atx",
        "name": "Titus Coat",
        "slogan": "Voluptas esse fugit quis esse fugit.",
        "description": "Ipsa eos id omnis aut voluptas voluptate praesentium rerum tempora. Earum maiores doloremque consequatur id voluptas fugit suscipit in. Ut enim sint. In error quo facere qui consequatur eum ipsa. Totam eos sequi enim. Soluta provident amet voluptas aliquam ut dolor.",
        "category": "Coat",
        "default_price": "884.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38341,
        "campus": "hr-atx",
        "name": "Florine Hoodie",
        "slogan": "Sapiente explicabo nihil libero.",
        "description": "Et eum laboriosam error rerum quia ut autem. Occaecati libero et nihil aperiam aliquam. Est at atque quo animi sed quo dignissimos at molestiae. Repellat rerum tempora qui earum amet. In omnis totam.",
        "category": "Hoodie",
        "default_price": "298.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38342,
        "campus": "hr-atx",
        "name": "Fletcher Boots",
        "slogan": "Qui quam omnis laudantium eaque magnam praesentium et qui autem.",
        "description": "Eveniet eaque sit laboriosam quisquam. Voluptates quisquam qui rerum nisi. Et et iusto nemo itaque suscipit nemo accusamus delectus recusandae. Quasi earum ut ad et alias vel ipsa facere nulla. Recusandae voluptatem nihil distinctio sequi.",
        "category": "Boots",
        "default_price": "585.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38343,
        "campus": "hr-atx",
        "name": "Abe Shirt",
        "slogan": "Maxime in et autem.",
        "description": "Saepe voluptas autem molestias magnam deleniti commodi omnis est. Unde dolorem dolores. Vel laudantium unde ipsa deleniti. Delectus eveniet aut excepturi ipsa aliquam consequatur. Atque qui tempore rem ut est debitis omnis.",
        "category": "Shirt",
        "default_price": "777.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38344,
        "campus": "hr-atx",
        "name": "Presley 1700 Jacket",
        "slogan": "Rem et ratione aut qui necessitatibus aliquam optio aut.",
        "description": "Consequatur eius distinctio neque rerum. Dolor aut placeat ipsam illum et sapiente in aspernatur odio. Veritatis recusandae voluptas tempora dolor sed possimus est quas non. Eum nobis consequuntur aut est. Autem deleniti nemo est enim sed deleniti unde.",
        "category": "Jacket",
        "default_price": "861.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38345,
        "campus": "hr-atx",
        "name": "Bettie Boots",
        "slogan": "Ullam deleniti et blanditiis.",
        "description": "Porro dicta earum suscipit facere quasi libero sit et doloremque. Atque ea cum error voluptate velit consequatur consectetur error. Qui illum consequatur sed est quo ad rerum ut.",
        "category": "Boots",
        "default_price": "820.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38346,
        "campus": "hr-atx",
        "name": "Clement Shorts",
        "slogan": "Ratione molestiae dolor iste aut.",
        "description": "Tempore harum unde accusamus. Et cumque earum vel reiciendis quaerat doloribus sunt dolor omnis. Minus ipsam ducimus similique dicta quo ex. Corrupti consequatur alias suscipit repudiandae. Commodi ut dolor et excepturi voluptatem. Optio expedita rem dolores aperiam.",
        "category": "Shorts",
        "default_price": "995.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38347,
        "campus": "hr-atx",
        "name": "Gia Dress",
        "slogan": "Enim quae est optio voluptates.",
        "description": "Ipsam nostrum quia. Aut suscipit provident incidunt laboriosam esse qui. Veniam officia illo et debitis eveniet. A qui sint voluptatem. Sed qui totam ut qui ut asperiores et. Qui consequatur rerum sapiente non rerum.",
        "category": "Dress",
        "default_price": "254.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38348,
        "campus": "hr-atx",
        "name": "Gianni Dress",
        "slogan": "Consectetur corporis pariatur suscipit iusto id.",
        "description": "Expedita rerum est. Explicabo qui illum consectetur. Neque accusantium qui facilis officiis consectetur autem. Sint saepe soluta facere placeat possimus fugiat vero doloremque accusantium.",
        "category": "Dress",
        "default_price": "535.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38349,
        "campus": "hr-atx",
        "name": "Dominique Coat",
        "slogan": "Ipsa dignissimos eos voluptas aut vero ad voluptatem necessitatibus placeat.",
        "description": "Dicta ut nesciunt vel minus est ducimus et nam. Aliquam ratione quos praesentium velit cum aut. Quia saepe consequatur totam facere alias quia esse eius ut. Ratione recusandae inventore vel quia molestiae culpa optio tempore rerum.",
        "category": "Coat",
        "default_price": "857.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38350,
        "campus": "hr-atx",
        "name": "Reynold Sweatpants",
        "slogan": "Quia dolorum incidunt nobis.",
        "description": "Dolore animi fuga fugiat dolorem aut quisquam amet. Voluptatem et in omnis velit tenetur consequatur molestiae delectus. Cum veniam labore dolorum quis. Animi aut nobis ea doloremque earum ut occaecati necessitatibus. Corporis sed sed ipsum voluptatem. Veniam voluptatem omnis corrupti ex debitis doloribus dolor magnam.",
        "category": "Sweatpants",
        "default_price": "353.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38351,
        "campus": "hr-atx",
        "name": "Russel Romper",
        "slogan": "Fugiat qui modi voluptatem.",
        "description": "Sapiente iure sequi quis fugit consequatur maxime nihil et. Sunt alias et dolor ut aut delectus vel eius. Rem harum ea quis.",
        "category": "Romper",
        "default_price": "927.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38352,
        "campus": "hr-atx",
        "name": "Maribel Cap",
        "slogan": "Dicta illo rem.",
        "description": "Rem vel eos sit porro quasi temporibus. Dolores culpa dolorum. Hic impedit consequatur doloribus. Quia aut impedit corporis incidunt eos ipsam alias id.",
        "category": "Cap",
        "default_price": "290.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38353,
        "campus": "hr-atx",
        "name": "Wilhelmine Cap",
        "slogan": "Fuga fugiat excepturi eum aliquam impedit.",
        "description": "Placeat incidunt consectetur quis. Aliquam minus minus. Sequi voluptas officiis itaque odio ut.",
        "category": "Cap",
        "default_price": "39.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38354,
        "campus": "hr-atx",
        "name": "Sidney Shoes",
        "slogan": "Fugiat atque deleniti iusto vero nam ab.",
        "description": "Quis fugit non aut perspiciatis laborum distinctio. Dicta repudiandae delectus dolorem fugit excepturi aspernatur et. Dolor et veniam.",
        "category": "Shoes",
        "default_price": "743.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38355,
        "campus": "hr-atx",
        "name": "Roberta Slacks",
        "slogan": "Et sit et nihil est.",
        "description": "Magni deleniti quia porro dolorum dolor adipisci voluptatem eum. Aperiam non delectus animi. Rerum quibusdam et quisquam sapiente maiores. Est doloremque voluptatem aut minus doloremque. Aut libero omnis perferendis.",
        "category": "Slacks",
        "default_price": "554.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38356,
        "campus": "hr-atx",
        "name": "Walker Backpack",
        "slogan": "Recusandae amet quia ea cumque repudiandae.",
        "description": "Alias eveniet ut aut rem non nihil et. At hic quae sint libero nihil saepe ullam. Atque harum est harum rerum. Quibusdam omnis consectetur rerum. Ipsa ratione delectus ea placeat et rerum.",
        "category": "Backpack",
        "default_price": "129.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38357,
        "campus": "hr-atx",
        "name": "Hannah Socks",
        "slogan": "Voluptate sed consequatur.",
        "description": "Est rem doloribus sint perspiciatis molestias nihil beatae corrupti labore. Enim qui optio molestiae nihil. Blanditiis qui sunt quia impedit voluptatum ut ex. Voluptates amet dolor dolores eos sequi aut libero laborum.",
        "category": "Socks",
        "default_price": "200.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38358,
        "campus": "hr-atx",
        "name": "Korey Sweater",
        "slogan": "Accusamus sint esse consequatur aut odio accusantium qui nihil aspernatur.",
        "description": "Saepe sit eius. Animi aut doloremque. Recusandae perferendis dolores odit consequatur veniam. Et rerum illum distinctio vel dolor et corrupti eligendi. Dicta dolorum neque vel.",
        "category": "Sweater",
        "default_price": "453.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38359,
        "campus": "hr-atx",
        "name": "Bradley Hat",
        "slogan": "Ullam exercitationem iure sapiente ut voluptatem earum non.",
        "description": "Ut quae sint qui nihil. Ipsam iste quaerat odio illo animi dolor quo beatae. Qui quo sapiente qui sint necessitatibus. Id molestias iusto sed sit esse vel. Iusto ipsam enim ut error error et.",
        "category": "Hat",
        "default_price": "861.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38360,
        "campus": "hr-atx",
        "name": "Matilda Sweatpants",
        "slogan": "Et perspiciatis autem aspernatur qui.",
        "description": "Esse ut consequatur corporis. Libero quis debitis est. Ut corporis rem ullam earum. Voluptatum non est sit earum rerum eius ducimus illum omnis. Quam consequatur soluta consequuntur est error.",
        "category": "Sweatpants",
        "default_price": "232.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38361,
        "campus": "hr-atx",
        "name": "Vivianne Hat",
        "slogan": "Voluptatem earum suscipit ut.",
        "description": "Praesentium consequatur est harum culpa aut. Repudiandae rem voluptates ad explicabo. Suscipit eum blanditiis aut.",
        "category": "Hat",
        "default_price": "188.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38362,
        "campus": "hr-atx",
        "name": "Regan Coat",
        "slogan": "Laborum repellat quia.",
        "description": "Recusandae quis error quos qui expedita nobis nostrum corporis. Saepe quo possimus id necessitatibus laborum et. Vero quibusdam quia. Doloremque sit eveniet. Iure dolor magni ut.",
        "category": "Coat",
        "default_price": "291.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    },
    {
        "id": 38363,
        "campus": "hr-atx",
        "name": "Fritz Trousers",
        "slogan": "Nisi natus aut ut.",
        "description": "Aspernatur sed ea molestiae asperiores est impedit velit. Molestias in eos et necessitatibus vel tenetur nemo. Tenetur nam quod odio molestiae nostrum voluptas.",
        "category": "Trousers",
        "default_price": "834.00",
        "created_at": "2021-08-13T14:38:01.002Z",
        "updated_at": "2021-08-13T14:38:01.002Z"
    }
]

export default exampleProducts;